name: CI/CD Pipeline

env:
  GO_VERSION: '1.21'
  GO_LINT_VERSION: 'v1.54.1'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Build
        run: make build

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./links-app.zip
          destination: s3://app-link-lambda/links-app.zip
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws_region: us-east-2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Test
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-2

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: link-stack
          template: cloudformation.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: "CAPABILITY_IAM, CAPABILITY_AUTO_EXPAND"
